sudo: true
dist: bionic
os: linux
language: bash
services:
  - docker
branches:
  only: 
    - master
before_install:
  - sed -i 's/#INSERT_HERE/COPY . \/oreka-src/g' .devcontainer/Dockerfile.orkaudio.build
  - echo "[Login]\nUsername = $MEGANAME \nPassword = $MEGAPASS" > .megarc
  - docker build -t oreka -f .devcontainer/Dockerfile.orkaudio.build .
script:
  -  docker run -i oreka bash /entrypoint.sh 
